### ISSUE TITLE
error: Not provided by fingerprint 41a41ba5073a55e873d7f7150e718211bff51409 find any certificate 

### ISSUE THREAD

**Issue by Huihh** [microsoft/TpmRCDecoder#1]
Hi, author:
    when I build this project on vs2022, but The following error occurs, please help me, what should I do, thank you very much

**Comment by RonaldAi** [comment]
I think that error is due to a missing publishing certificate. If you set up a Microsoft store account and download a certificate for your application, the right information should be populated in the project and allow you to build it.
